/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
 
    implementation("io.vertx:vertx-core:4.3.3")
    implementation("io.vertx:vertx-web:4.3.3")
    implementation("io.vertx:vertx-web-client:4.3.3")
    implementation("io.vertx:vertx-mqtt:4.3.3")
    
    /* Lib for working with MQTT (Paho) */
    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")
}


tasks.register<JavaExec>("run-smartroom-case1-superloop") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.smartroom.case1.RunSuperLoopController" 
}

tasks.register<JavaExec>("run-smartroom-case1-eventloop") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.smartroom.case1.RunSuperLoopController"
}

tasks.register<JavaExec>("run-smartroom-case2-pres-det-agent") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.smartroom.case2.RunPresenceDetectionAgent"
}

tasks.register<JavaExec>("run-smartroom-case2-light-sens-agent") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.smartroom.case2.RunLightSensingAgent"
}

tasks.register<JavaExec>("run-smartroom-case2-lamp-agent") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.smartroom.case2.RunLampControllerAgent"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}


// Apply a specific Java toolchain to ease working on different environments.
/*
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

application {
    // Define the main class for the application.
    // mainClass.set("sap.smartroom.App")
}
*/

