/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sap.escooters.launcher;


import java.util.Optional;

import sap.escooters.data_source_layer.*;
import sap.escooters.domain_layer.*;
import sap.escooters.presentation_layer.*;
import sap.escooters.service_layer.*;

public class EScooterManagementSystem {

    public static void main(String[] args) {

    	DataSourceLayer dataSourceLayer = new DataSourceLayerImpl("dbase");
    	DomainLayer domainLayer = new DomainLayerImpl();
    	ServiceLayer serviceLayer = new ServiceLayerImpl();
    	PresentationLayer presentationLayer = new PresentationLayerImpl(8081);
    	
    	dataSourceLayer.init(Optional.empty());
    	domainLayer.init(Optional.of(dataSourceLayer));
    	serviceLayer.init(Optional.of(domainLayer));
    	presentationLayer.init(Optional.of(serviceLayer));
    			
    	
    }
}
