/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    /* Framwork for event-driven/reactive systems (Vertx) */
    implementation("io.vertx:vertx-core:4.3.3")
    implementation("io.vertx:vertx-web:4.3.3")
    implementation("io.vertx:vertx-web-client:4.3.3")
    implementation("io.vertx:vertx-mqtt:4.3.3")
    
    /* Lib for working with MQTT (Paho) */
    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")

    /* Lib for working with CoAP (Californium) */
    implementation("org.eclipse.californium:californium-core:2.6.4")


    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:32.1.1-jre")
}

tasks.register<JavaExec>("run-lamp-thing") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.lamp_thing.impl.RunLampThingService"
}

tasks.register<JavaExec>("run-lamp-dt") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.lamp_dt.impl.RunLampDTService"
}

tasks.register<JavaExec>("run-lamp-dt-consumer") {
    classpath = sourceSets["main"].runtimeClasspath
    mainClass = "sap.lamp_dt.consumer.RunLampDTConsumer"
}

/*
application {
    // Define the main class for the application.
    mainClass.set("sap.smartroom.App")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}
*/

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
