package sap.pres_detect_thing.impl;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;

/**
 * Presence Detection Thing API 
 *   
 * @author aricci
 *
 */
public interface PresDetectThingAPI {
	
	Future<JsonObject> getTD();
	
	/* properties */

	Future<Boolean> isDetected();
	
	/**
	 * Subscribe to events generated by the light device
	 * 
	 * @param handler
	 * @return
	 */
	Future<Void> subscribe(Handler<JsonObject> handler);
}
